### ISSUE TITLE
Open in new window/tab

### ISSUE THREAD

**Issue by ryryan** [mad-web/nova-telescope-link#1]
Is it possible to customise the target of the link?

**Comment by slavarazum** [comment]
No, it isn't a custom link. Target takes from `telescope.path` config value.

**Comment by slavarazum** [comment]
Got it, good idea. I will provide this feature in a next release. Also will I provide it for the [mad-web/nova-horizon-link](https://github.com/mad-web/nova-horizon-link). Thanks for getting in touch!

**Comment by ryryan** [comment]
I’m happy to give it a go via a PR.

**Comment by laraning** [comment]
Need it too :) congrats for the package, really clean code!

**Comment by slavarazum** [comment]
Thanks for the feedback! It's really motivate.

**Comment by ryryan** [comment]
Thanks for accepting the PR. Does a new release need to be added?

**Comment by slavarazum** [comment]
Just tagged [new 0.2.0 release](https://github.com/mad-web/nova-telescope-link/releases/tag/0.2.0).
Also provided ability to use _Fluent Interface_ and disabled ability to pass null as `$label` parameter.

**Comment by ryryan** [comment]
Great, even cleaner code.
