### ISSUE TITLE
Telescope v1.0.0

### ISSUE THREAD

**Issue by mvdnbrk** [mad-web/nova-telescope-link#3]
Laravel Telescope [v1.0.0](https://github.com/laravel/telescope/releases/tag/v1.0.0) was just released.

Can you bump the version to 1.0 in the [`composer.json`](https://github.com/mad-web/nova-telescope-link/blob/master/composer.json#L23) file to reflect this?
Thanks!

😄

**Comment by slavarazum** [comment]
Thanks for your PR 😀
